[2025-07-19T23:19:20.952+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: build_ml_features.validate_features manual__2025-07-19T23:14:12.012499+00:00 [queued]>
[2025-07-19T23:19:20.955+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: build_ml_features.validate_features manual__2025-07-19T23:14:12.012499+00:00 [queued]>
[2025-07-19T23:19:20.955+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-19T23:19:20.959+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_features> on 2025-07-19 23:14:12.012499+00:00
[2025-07-19T23:19:20.963+0000] {standard_task_runner.py:60} INFO - Started process 1100 to run task
[2025-07-19T23:19:20.964+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'build_ml_features', 'validate_features', 'manual__2025-07-19T23:14:12.012499+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/build_ml_features_dag.py', '--cfg-path', '/tmp/tmpvfd6fgzx']
[2025-07-19T23:19:20.965+0000] {standard_task_runner.py:88} INFO - Job 200: Subtask validate_features
[2025-07-19T23:19:20.980+0000] {task_command.py:423} INFO - Running <TaskInstance: build_ml_features.validate_features manual__2025-07-19T23:14:12.012499+00:00 [running]> on host bc2a27ae9be1
[2025-07-19T23:19:21.006+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='build_ml_features' AIRFLOW_CTX_TASK_ID='validate_features' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T23:14:12.012499+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-19T23:14:12.012499+00:00'
[2025-07-19T23:19:21.026+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-19T23:19:21.027+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-19T23:19:21.027+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T23:19:21.028+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T23:19:21.040+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-19T23:19:21.040+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-19T23:19:21.040+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T23:19:21.040+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T23:19:21.040+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T23:19:21.072+0000] {validator.py:1461} INFO - 	12 expectation(s) included in expectation_suite.
[2025-07-19T23:19:21.139+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/62 [00:00<?, ?it/s]
[2025-07-19T23:19:21.139+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/62 [00:00<?, ?it/s]
[2025-07-19T23:19:21.139+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   3%|3         | 2/62 [00:00<00:00, 5065.58it/s]
[2025-07-19T23:19:21.153+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   3%|3         | 2/62 [00:00<00:00, 145.57it/s] 
[2025-07-19T23:19:21.153+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   5%|4         | 3/62 [00:00<00:00, 214.86it/s]
[2025-07-19T23:19:21.166+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   5%|4         | 3/62 [00:00<00:00, 110.68it/s]
[2025-07-19T23:19:21.170+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  26%|##5       | 16/62 [00:00<00:00, 522.31it/s]
[2025-07-19T23:19:21.180+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  26%|##5       | 16/62 [00:00<00:00, 389.27it/s]
[2025-07-19T23:19:21.191+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 1193.90it/s]
[2025-07-19T23:19:21.195+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 1105.12it/s]
[2025-07-19T23:19:21.195+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 1102.31it/s]
[2025-07-19T23:19:21.195+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 1099.74it/s]
[2025-07-19T23:19:21.341+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/build_ml_features_dag.py", line 112, in validate_features
    index_paths = ctx.build_data_docs(site_name="s3_cloudfront")
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 266, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
TypeError: build_data_docs() got an unexpected keyword argument 'site_name'
[2025-07-19T23:19:21.346+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=build_ml_features, task_id=validate_features, execution_date=20250719T231412, start_date=20250719T231920, end_date=20250719T231921
[2025-07-19T23:19:21.353+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 200 for task validate_features (build_data_docs() got an unexpected keyword argument 'site_name'; 1100)
[2025-07-19T23:19:21.363+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-19T23:19:21.374+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
