[2025-07-17T18:13:31.639+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T18:13:27.226524+00:00 [queued]>
[2025-07-17T18:13:31.643+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T18:13:27.226524+00:00 [queued]>
[2025-07-17T18:13:31.643+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-07-17T18:13:31.647+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_dataframe> on 2025-07-17 18:13:27.226524+00:00
[2025-07-17T18:13:31.650+0000] {standard_task_runner.py:60} INFO - Started process 356 to run task
[2025-07-17T18:13:31.652+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'curated_market_dq', 'validate_dataframe', 'manual__2025-07-17T18:13:27.226524+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/curated_market_dq_dag.py', '--cfg-path', '/tmp/tmpn83gjww7']
[2025-07-17T18:13:31.653+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask validate_dataframe
[2025-07-17T18:13:31.672+0000] {task_command.py:423} INFO - Running <TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T18:13:27.226524+00:00 [running]> on host 631ad56c707c
[2025-07-17T18:13:31.727+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='curated_market_dq' AIRFLOW_CTX_TASK_ID='validate_dataframe' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T18:13:27.226524+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-17T18:13:27.226524+00:00'
[2025-07-17T18:13:31.748+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-17T18:13:31.749+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-17T18:13:31.750+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T18:13:31.763+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-17T18:13:31.764+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-17T18:13:31.764+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T18:13:31.764+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T18:13:31.787+0000] {validator.py:1461} INFO - 	7 expectation(s) included in expectation_suite.
[2025-07-17T18:13:31.816+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/23 [00:00<?, ?it/s]
[2025-07-17T18:13:31.816+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/23 [00:00<?, ?it/s]
[2025-07-17T18:13:31.816+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   9%|8         | 2/23 [00:00<00:00, 5115.00it/s]
[2025-07-17T18:13:31.822+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   9%|8         | 2/23 [00:00<00:00, 344.77it/s] 
[2025-07-17T18:13:31.822+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 499.60it/s]
[2025-07-17T18:13:31.827+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 266.76it/s]
[2025-07-17T18:13:31.834+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 166.36it/s]
[2025-07-17T18:13:31.840+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 123.83it/s]
[2025-07-17T18:13:31.846+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 99.35it/s] 
[2025-07-17T18:13:31.852+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 82.70it/s]
[2025-07-17T18:13:31.858+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 71.14it/s]
[2025-07-17T18:13:31.864+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 62.22it/s]
[2025-07-17T18:13:31.865+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  22%|##1       | 5/23 [00:00<00:00, 102.13it/s]
[2025-07-17T18:13:31.870+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  22%|##1       | 5/23 [00:00<00:00, 93.11it/s] 
[2025-07-17T18:13:31.872+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  57%|#####6    | 13/23 [00:00<00:00, 232.51it/s]
[2025-07-17T18:13:31.875+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  57%|#####6    | 13/23 [00:00<00:00, 219.27it/s]
[2025-07-17T18:13:31.876+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  57%|#####6    | 13/23 [00:00<00:00, 217.90it/s]
[2025-07-17T18:13:31.876+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  57%|#####6    | 13/23 [00:00<00:00, 217.33it/s]
[2025-07-17T18:13:31.995+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/curated_market_dq_dag.py", line 86, in validate_dataframe
    raise ValueError("❌ GE validation failed")
ValueError: ❌ GE validation failed
[2025-07-17T18:13:32.000+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=curated_market_dq, task_id=validate_dataframe, execution_date=20250717T181327, start_date=20250717T181331, end_date=20250717T181332
[2025-07-17T18:13:32.005+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task validate_dataframe (❌ GE validation failed; 356)
[2025-07-17T18:13:32.011+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-17T18:13:32.020+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
