[2025-07-17T18:18:33.546+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T18:13:27.226524+00:00 [queued]>
[2025-07-17T18:18:33.548+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T18:13:27.226524+00:00 [queued]>
[2025-07-17T18:18:33.548+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-07-17T18:18:33.552+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_dataframe> on 2025-07-17 18:13:27.226524+00:00
[2025-07-17T18:18:33.556+0000] {standard_task_runner.py:60} INFO - Started process 522 to run task
[2025-07-17T18:18:33.558+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'curated_market_dq', 'validate_dataframe', 'manual__2025-07-17T18:13:27.226524+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/curated_market_dq_dag.py', '--cfg-path', '/tmp/tmptgxq0641']
[2025-07-17T18:18:33.558+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask validate_dataframe
[2025-07-17T18:18:33.581+0000] {task_command.py:423} INFO - Running <TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T18:13:27.226524+00:00 [running]> on host 631ad56c707c
[2025-07-17T18:18:33.631+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='curated_market_dq' AIRFLOW_CTX_TASK_ID='validate_dataframe' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T18:13:27.226524+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-17T18:13:27.226524+00:00'
[2025-07-17T18:18:33.651+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-17T18:18:33.652+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-17T18:18:33.652+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T18:18:33.664+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-17T18:18:33.665+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-17T18:18:33.665+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T18:18:33.665+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T18:18:33.685+0000] {validator.py:1461} INFO - 	7 expectation(s) included in expectation_suite.
[2025-07-17T18:18:33.714+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/23 [00:00<?, ?it/s]
[2025-07-17T18:18:33.714+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/23 [00:00<?, ?it/s]
[2025-07-17T18:18:33.715+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   9%|8         | 2/23 [00:00<00:00, 5162.22it/s]
[2025-07-17T18:18:33.720+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   9%|8         | 2/23 [00:00<00:00, 349.31it/s] 
[2025-07-17T18:18:33.720+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 504.47it/s]
[2025-07-17T18:18:33.725+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 270.77it/s]
[2025-07-17T18:18:33.732+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 168.25it/s]
[2025-07-17T18:18:33.738+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 126.20it/s]
[2025-07-17T18:18:33.744+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 101.23it/s]
[2025-07-17T18:18:33.750+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 84.10it/s] 
[2025-07-17T18:18:33.756+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 72.16it/s]
[2025-07-17T18:18:33.762+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 62.91it/s]
[2025-07-17T18:18:33.763+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  22%|##1       | 5/23 [00:00<00:00, 103.31it/s]
[2025-07-17T18:18:33.767+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  22%|##1       | 5/23 [00:00<00:00, 94.15it/s] 
[2025-07-17T18:18:33.769+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  57%|#####6    | 13/23 [00:00<00:00, 235.34it/s]
[2025-07-17T18:18:33.773+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  57%|#####6    | 13/23 [00:00<00:00, 222.04it/s]
[2025-07-17T18:18:33.773+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  57%|#####6    | 13/23 [00:00<00:00, 221.22it/s]
[2025-07-17T18:18:33.773+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  57%|#####6    | 13/23 [00:00<00:00, 220.70it/s]
[2025-07-17T18:18:33.895+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/curated_market_dq_dag.py", line 86, in validate_dataframe
    raise ValueError("❌ GE validation failed")
ValueError: ❌ GE validation failed
[2025-07-17T18:18:33.900+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=curated_market_dq, task_id=validate_dataframe, execution_date=20250717T181327, start_date=20250717T181833, end_date=20250717T181833
[2025-07-17T18:18:33.905+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task validate_dataframe (❌ GE validation failed; 522)
[2025-07-17T18:18:33.951+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-17T18:18:33.960+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
