[2025-07-19T14:00:17.214+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: build_ml_features.transform_features manual__2025-07-19T14:00:13.282536+00:00 [queued]>
[2025-07-19T14:00:17.233+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: build_ml_features.transform_features manual__2025-07-19T14:00:13.282536+00:00 [queued]>
[2025-07-19T14:00:17.233+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-19T14:00:17.243+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_features> on 2025-07-19 14:00:13.282536+00:00
[2025-07-19T14:00:17.249+0000] {standard_task_runner.py:60} INFO - Started process 1121 to run task
[2025-07-19T14:00:17.251+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'build_ml_features', 'transform_features', 'manual__2025-07-19T14:00:13.282536+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/build_ml_features_dag.py', '--cfg-path', '/tmp/tmpt_dt619r']
[2025-07-19T14:00:17.252+0000] {standard_task_runner.py:88} INFO - Job 82: Subtask transform_features
[2025-07-19T14:00:17.271+0000] {task_command.py:423} INFO - Running <TaskInstance: build_ml_features.transform_features manual__2025-07-19T14:00:13.282536+00:00 [running]> on host e05da308c0da
[2025-07-19T14:00:17.306+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='build_ml_features' AIRFLOW_CTX_TASK_ID='transform_features' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T14:00:13.282536+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-19T14:00:13.282536+00:00'
[2025-07-19T14:00:17.313+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/build_ml_features_dag.py", line 79, in transform_features
    df.pipe(compute_momentum)
NameError: name 'compute_momentum' is not defined
[2025-07-19T14:00:17.319+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=build_ml_features, task_id=transform_features, execution_date=20250719T140013, start_date=20250719T140017, end_date=20250719T140017
[2025-07-19T14:00:17.323+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 82 for task transform_features (name 'compute_momentum' is not defined; 1121)
[2025-07-19T14:00:17.349+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-19T14:00:17.358+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
