[2025-07-19T14:57:14.757+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: build_ml_features.validate_features manual__2025-07-19T14:53:51.036871+00:00 [queued]>
[2025-07-19T14:57:14.760+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: build_ml_features.validate_features manual__2025-07-19T14:53:51.036871+00:00 [queued]>
[2025-07-19T14:57:14.760+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-07-19T14:57:14.763+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_features> on 2025-07-19 14:53:51.036871+00:00
[2025-07-19T14:57:14.767+0000] {standard_task_runner.py:60} INFO - Started process 400 to run task
[2025-07-19T14:57:14.769+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'build_ml_features', 'validate_features', 'manual__2025-07-19T14:53:51.036871+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/build_ml_features_dag.py', '--cfg-path', '/tmp/tmpqcxw2sv3']
[2025-07-19T14:57:14.769+0000] {standard_task_runner.py:88} INFO - Job 137: Subtask validate_features
[2025-07-19T14:57:14.787+0000] {task_command.py:423} INFO - Running <TaskInstance: build_ml_features.validate_features manual__2025-07-19T14:53:51.036871+00:00 [running]> on host 78a06dccabbd
[2025-07-19T14:57:14.820+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='build_ml_features' AIRFLOW_CTX_TASK_ID='validate_features' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T14:53:51.036871+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-19T14:53:51.036871+00:00'
[2025-07-19T14:57:14.838+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-19T14:57:14.839+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-19T14:57:14.840+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T14:57:14.840+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T14:57:14.853+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-19T14:57:14.853+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-19T14:57:14.853+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T14:57:14.853+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T14:57:14.853+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T14:57:14.889+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

[2025-07-19T14:57:14.896+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]
[2025-07-19T14:57:14.896+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]
[2025-07-19T14:57:14.896+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  33%|###3      | 2/6 [00:00<00:00, 5035.18it/s]
[2025-07-19T14:57:14.897+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  33%|###3      | 2/6 [00:00<00:00, 1678.73it/s]
[2025-07-19T14:57:14.897+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  50%|#####     | 3/6 [00:00<00:00, 2148.35it/s]
[2025-07-19T14:57:14.898+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  50%|#####     | 3/6 [00:00<00:00, 1444.65it/s]
[2025-07-19T14:57:14.898+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  67%|######6   | 4/6 [00:00<00:00, 1589.35it/s]
[2025-07-19T14:57:14.899+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  67%|######6   | 4/6 [00:00<00:00, 1284.53it/s]
[2025-07-19T14:57:14.900+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1584.95it/s]
[2025-07-19T14:57:14.900+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1458.63it/s]
[2025-07-19T14:57:14.900+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1427.69it/s]
[2025-07-19T14:57:14.900+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1394.00it/s]
[2025-07-19T14:57:14.901+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

[2025-07-19T14:57:14.904+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]
[2025-07-19T14:57:14.904+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]
[2025-07-19T14:57:14.904+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  33%|###3      | 2/6 [00:00<00:00, 7584.64it/s]
[2025-07-19T14:57:14.905+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  33%|###3      | 2/6 [00:00<00:00, 2005.40it/s]
[2025-07-19T14:57:14.905+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  50%|#####     | 3/6 [00:00<00:00, 2566.89it/s]
[2025-07-19T14:57:14.906+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  50%|#####     | 3/6 [00:00<00:00, 1652.82it/s]
[2025-07-19T14:57:14.906+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  67%|######6   | 4/6 [00:00<00:00, 1878.96it/s]
[2025-07-19T14:57:14.907+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  67%|######6   | 4/6 [00:00<00:00, 1497.30it/s]
[2025-07-19T14:57:14.907+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1879.17it/s]
[2025-07-19T14:57:14.908+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1696.38it/s]
[2025-07-19T14:57:14.908+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1648.49it/s]
[2025-07-19T14:57:14.908+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1602.00it/s]
[2025-07-19T14:57:14.908+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

[2025-07-19T14:57:14.911+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]
[2025-07-19T14:57:14.911+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]
[2025-07-19T14:57:14.912+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  33%|###3      | 2/6 [00:00<00:00, 7966.39it/s]
[2025-07-19T14:57:14.912+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  33%|###3      | 2/6 [00:00<00:00, 2084.13it/s]
[2025-07-19T14:57:14.913+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  50%|#####     | 3/6 [00:00<00:00, 2663.05it/s]
[2025-07-19T14:57:14.913+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  50%|#####     | 3/6 [00:00<00:00, 1695.81it/s]
[2025-07-19T14:57:14.914+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  67%|######6   | 4/6 [00:00<00:00, 1914.33it/s]
[2025-07-19T14:57:14.914+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  67%|######6   | 4/6 [00:00<00:00, 1539.48it/s]
[2025-07-19T14:57:14.915+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1919.00it/s]
[2025-07-19T14:57:14.915+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1756.16it/s]
[2025-07-19T14:57:14.915+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1708.13it/s]
[2025-07-19T14:57:14.915+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1660.34it/s]
[2025-07-19T14:57:14.916+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

[2025-07-19T14:57:14.919+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]
[2025-07-19T14:57:14.919+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]
[2025-07-19T14:57:14.919+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  33%|###3      | 2/6 [00:00<00:00, 8232.20it/s]
[2025-07-19T14:57:14.920+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  33%|###3      | 2/6 [00:00<00:00, 2093.49it/s]
[2025-07-19T14:57:14.920+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  50%|#####     | 3/6 [00:00<00:00, 2685.21it/s]
[2025-07-19T14:57:14.921+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  50%|#####     | 3/6 [00:00<00:00, 1713.13it/s]
[2025-07-19T14:57:14.921+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  67%|######6   | 4/6 [00:00<00:00, 1962.02it/s]
[2025-07-19T14:57:14.921+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  67%|######6   | 4/6 [00:00<00:00, 1568.40it/s]
[2025-07-19T14:57:14.922+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1969.00it/s]
[2025-07-19T14:57:14.922+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1799.49it/s]
[2025-07-19T14:57:14.922+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1750.30it/s]
[2025-07-19T14:57:14.922+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1700.39it/s]
[2025-07-19T14:57:14.923+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

[2025-07-19T14:57:14.926+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]
[2025-07-19T14:57:14.926+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]
[2025-07-19T14:57:14.926+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  33%|###3      | 2/6 [00:00<00:00, 8621.39it/s]
[2025-07-19T14:57:14.927+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  33%|###3      | 2/6 [00:00<00:00, 2157.01it/s]
[2025-07-19T14:57:14.927+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  50%|#####     | 3/6 [00:00<00:00, 2737.20it/s]
[2025-07-19T14:57:14.928+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  50%|#####     | 3/6 [00:00<00:00, 1717.33it/s]
[2025-07-19T14:57:14.928+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  67%|######6   | 4/6 [00:00<00:00, 1969.62it/s]
[2025-07-19T14:57:14.929+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  67%|######6   | 4/6 [00:00<00:00, 1566.94it/s]
[2025-07-19T14:57:14.929+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1977.05it/s]
[2025-07-19T14:57:14.929+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1800.77it/s]
[2025-07-19T14:57:14.930+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1740.74it/s]
[2025-07-19T14:57:14.930+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 6/6 [00:00<00:00, 1691.93it/s]
[2025-07-19T14:57:14.930+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

[2025-07-19T14:57:14.936+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-07-19T14:57:14.936+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-07-19T14:57:14.936+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 8914.57it/s]
[2025-07-19T14:57:14.938+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 1273.32it/s]
[2025-07-19T14:57:14.938+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  38%|###7      | 3/8 [00:00<00:00, 1726.05it/s]
[2025-07-19T14:57:14.939+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  38%|###7      | 3/8 [00:00<00:00, 1004.46it/s]
[2025-07-19T14:57:14.940+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 1286.60it/s]
[2025-07-19T14:57:14.941+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 1026.31it/s]
[2025-07-19T14:57:14.942+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 1391.84it/s]
[2025-07-19T14:57:14.942+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 1281.54it/s]
[2025-07-19T14:57:14.942+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 1260.59it/s]
[2025-07-19T14:57:14.942+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 1241.74it/s]
[2025-07-19T14:57:14.944+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

[2025-07-19T14:57:14.949+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-07-19T14:57:14.949+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-07-19T14:57:14.949+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 9000.65it/s]
[2025-07-19T14:57:14.950+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  25%|##5       | 2/8 [00:00<00:00, 1336.19it/s]
[2025-07-19T14:57:14.950+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  38%|###7      | 3/8 [00:00<00:00, 1804.52it/s]
[2025-07-19T14:57:14.952+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  38%|###7      | 3/8 [00:00<00:00, 1046.48it/s]
[2025-07-19T14:57:14.952+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 1388.75it/s]
[2025-07-19T14:57:14.953+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  62%|######2   | 5/8 [00:00<00:00, 1097.41it/s]
[2025-07-19T14:57:14.954+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 1485.96it/s]
[2025-07-19T14:57:14.955+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 1365.56it/s]
[2025-07-19T14:57:14.955+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 1343.31it/s]
[2025-07-19T14:57:14.955+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 8/8 [00:00<00:00, 1313.80it/s]
[2025-07-19T14:57:14.956+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

[2025-07-19T14:57:14.959+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]
[2025-07-19T14:57:14.959+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]
[2025-07-19T14:57:14.959+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  33%|###3      | 2/6 [00:00<00:00, 8774.69it/s]
[2025-07-19T14:57:14.960+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  33%|###3      | 2/6 [00:00<00:00, 2143.23it/s]
[2025-07-19T14:57:14.960+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  50%|#####     | 3/6 [00:00<00:00, 2745.56it/s]
[2025-07-19T14:57:14.961+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  50%|#####     | 3/6 [00:00<00:00, 1748.11it/s]
[2025-07-19T14:57:14.961+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 548, in _process_direct_and_bundled_metric_computation_configurations
    ] = metric_computation_configuration.metric_fn(  # type: ignore[misc] # F not callable
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/expectations/metrics/metric_provider.py", line 100, in inner_func
    return metric_fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/expectations/metrics/map_metric_provider/column_condition_partial.py", line 96, in inner_func
    metric_domain_kwargs = get_dbms_compatible_metric_domain_kwargs(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/expectations/metrics/util.py", line 703, in get_dbms_compatible_metric_domain_kwargs
    column_name: str | sqlalchemy.quoted_name = get_dbms_compatible_column_names(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/expectations/metrics/util.py", line 777, in get_dbms_compatible_column_names
    _verify_column_names_exist_and_get_normalized_typed_column_names_map(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/expectations/metrics/util.py", line 873, in _verify_column_names_exist_and_get_normalized_typed_column_names_map
    raise gx_exceptions.InvalidMetricAccessorDomainKwargsKeyError(
great_expectations.exceptions.exceptions.InvalidMetricAccessorDomainKwargsKeyError: Error: The column "macd" in BatchData does not exist.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/build_ml_features_dag.py", line 113, in validate_features
    validator.expect_column_values_to_not_be_null("macd")
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/validator/validator.py", line 590, in inst_expectation
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/validator/validator.py", line 553, in inst_expectation
    validation_result = expectation.validate(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/expectations/expectation.py", line 1314, in validate
    ] = validator.graph_validate(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/validator/validator.py", line 1065, in graph_validate
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/validator/validator.py", line 1044, in graph_validate
    ) = self._resolve_suite_level_graph_and_process_metric_evaluation_errors(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/validator/validator.py", line 1200, in _resolve_suite_level_graph_and_process_metric_evaluation_errors
    ) = self._metrics_calculator.resolve_validation_graph(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/validator/metrics_calculator.py", line 274, in resolve_validation_graph
    resolved_metrics, aborted_metrics_info = graph.resolve(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/validator/validation_graph.py", line 202, in resolve
    aborted_metrics_info: _AbortedMetricsInfoDict = self._resolve(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/validator/validation_graph.py", line 302, in _resolve
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/validator/validation_graph.py", line 269, in _resolve
    self._execution_engine.resolve_metrics(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 283, in resolve_metrics
    return self._process_direct_and_bundled_metric_computation_configurations(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 552, in _process_direct_and_bundled_metric_computation_configurations
    raise gx_exceptions.MetricResolutionError(
great_expectations.exceptions.exceptions.MetricResolutionError: Error: The column "macd" in BatchData does not exist.
[2025-07-19T14:57:14.965+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=build_ml_features, task_id=validate_features, execution_date=20250719T145351, start_date=20250719T145714, end_date=20250719T145714
[2025-07-19T14:57:14.969+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 137 for task validate_features (Error: The column "macd" in BatchData does not exist.; 400)
[2025-07-19T14:57:14.995+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-19T14:57:15.001+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
