[2025-07-17T00:00:18.224+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe scheduled__2025-07-16T00:00:00+00:00 [queued]>
[2025-07-17T00:00:18.246+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe scheduled__2025-07-16T00:00:00+00:00 [queued]>
[2025-07-17T00:00:18.247+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-07-17T00:00:18.291+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_dataframe> on 2025-07-16 00:00:00+00:00
[2025-07-17T00:00:18.311+0000] {standard_task_runner.py:60} INFO - Started process 460 to run task
[2025-07-17T00:00:18.316+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'curated_market_dq', 'validate_dataframe', 'scheduled__2025-07-16T00:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/curated_market_dq_dag.py', '--cfg-path', '/tmp/tmpgehml9kf']
[2025-07-17T00:00:18.318+0000] {standard_task_runner.py:88} INFO - Job 104: Subtask validate_dataframe
[2025-07-17T00:00:18.411+0000] {task_command.py:423} INFO - Running <TaskInstance: curated_market_dq.validate_dataframe scheduled__2025-07-16T00:00:00+00:00 [running]> on host 189e939b6cc2
[2025-07-17T00:00:18.788+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='curated_market_dq' AIRFLOW_CTX_TASK_ID='validate_dataframe' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-16T00:00:00+00:00'
[2025-07-17T00:00:19.038+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-17T00:00:19.045+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-17T00:00:19.047+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T00:00:19.197+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-17T00:00:19.199+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-17T00:00:19.200+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T00:00:19.203+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T00:00:19.401+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/curated_market_dq_dag.py", line 82, in validate_dataframe
    result = ctx.run_checkpoint(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 266, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2108, in run_checkpoint
    return self._run_checkpoint(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2152, in _run_checkpoint
    result: CheckpointResult = checkpoint.run_with_runtime_args(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/checkpoint/checkpoint.py", line 915, in run_with_runtime_args
    return self.run(**checkpoint_run_arguments)
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 266, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/checkpoint/checkpoint.py", line 315, in run
    self._run_validation(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/checkpoint/checkpoint.py", line 480, in _run_validation
    validator: Validator = self._validator or self.data_context.get_validator(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2375, in get_validator
    self.get_batch_list(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 266, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2544, in get_batch_list
    return self._get_batch_list(
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 2625, in _get_batch_list
    return datasource.get_batch_list_from_batch_request(batch_request=result)
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/datasource/fluent/interfaces.py", line 474, in get_batch_list_from_batch_request
    return data_asset.get_batch_list_from_batch_request(batch_request)
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/datasource/fluent/pandas_datasource.py", line 410, in get_batch_list_from_batch_request
    self._validate_batch_request(batch_request)
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations/datasource/fluent/pandas_datasource.py", line 201, in _validate_batch_request
    and not batch_request.options
AttributeError: 'RuntimeBatchRequest' object has no attribute 'options'
[2025-07-17T00:00:19.465+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=curated_market_dq, task_id=validate_dataframe, execution_date=20250716T000000, start_date=20250717T000018, end_date=20250717T000019
[2025-07-17T00:00:19.519+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 104 for task validate_dataframe ('RuntimeBatchRequest' object has no attribute 'options'; 460)
[2025-07-17T00:00:19.587+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-17T00:00:19.854+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-17T18:06:21.720+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe scheduled__2025-07-16T00:00:00+00:00 [queued]>
[2025-07-17T18:06:21.722+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe scheduled__2025-07-16T00:00:00+00:00 [queued]>
[2025-07-17T18:06:21.722+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-07-17T18:06:21.726+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_dataframe> on 2025-07-16 00:00:00+00:00
[2025-07-17T18:06:21.729+0000] {standard_task_runner.py:60} INFO - Started process 131 to run task
[2025-07-17T18:06:21.731+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'curated_market_dq', 'validate_dataframe', 'scheduled__2025-07-16T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/curated_market_dq_dag.py', '--cfg-path', '/tmp/tmpqwti5j8c']
[2025-07-17T18:06:21.731+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask validate_dataframe
[2025-07-17T18:06:21.749+0000] {task_command.py:423} INFO - Running <TaskInstance: curated_market_dq.validate_dataframe scheduled__2025-07-16T00:00:00+00:00 [running]> on host 631ad56c707c
[2025-07-17T18:06:21.794+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='curated_market_dq' AIRFLOW_CTX_TASK_ID='validate_dataframe' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-16T00:00:00+00:00'
[2025-07-17T18:06:21.813+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-17T18:06:21.814+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-17T18:06:21.814+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T18:06:21.826+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-17T18:06:21.827+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-17T18:06:21.827+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T18:06:21.827+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T18:06:21.845+0000] {validator.py:1461} INFO - 	7 expectation(s) included in expectation_suite.
[2025-07-17T18:06:21.874+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/23 [00:00<?, ?it/s]
[2025-07-17T18:06:21.874+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/23 [00:00<?, ?it/s]
[2025-07-17T18:06:21.875+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   9%|8         | 2/23 [00:00<00:00, 5065.58it/s]
[2025-07-17T18:06:21.880+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   9%|8         | 2/23 [00:00<00:00, 331.37it/s] 
[2025-07-17T18:06:21.880+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 481.05it/s]
[2025-07-17T18:06:21.886+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 260.29it/s]
[2025-07-17T18:06:21.887+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  30%|###       | 7/23 [00:00<00:00, 542.34it/s]
[2025-07-17T18:06:21.892+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  30%|###       | 7/23 [00:00<00:00, 403.60it/s]
[2025-07-17T18:06:21.896+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 23/23 [00:00<00:00, 1062.42it/s]
[2025-07-17T18:06:21.898+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 23/23 [00:00<00:00, 978.58it/s] 
[2025-07-17T18:06:21.898+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 23/23 [00:00<00:00, 973.95it/s]
[2025-07-17T18:06:21.898+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 23/23 [00:00<00:00, 968.88it/s]
[2025-07-17T18:06:22.030+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-17T18:06:22.034+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=curated_market_dq, task_id=validate_dataframe, execution_date=20250716T000000, start_date=20250717T180621, end_date=20250717T180622
[2025-07-17T18:06:22.079+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-17T18:06:22.088+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
