[2025-07-17T19:08:10.411+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T19:08:05.455518+00:00 [queued]>
[2025-07-17T19:08:10.413+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T19:08:05.455518+00:00 [queued]>
[2025-07-17T19:08:10.413+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-07-17T19:08:10.417+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_dataframe> on 2025-07-17 19:08:05.455518+00:00
[2025-07-17T19:08:10.420+0000] {standard_task_runner.py:60} INFO - Started process 473 to run task
[2025-07-17T19:08:10.422+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'curated_market_dq', 'validate_dataframe', 'manual__2025-07-17T19:08:05.455518+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/curated_market_dq_dag.py', '--cfg-path', '/tmp/tmphuv7fh74']
[2025-07-17T19:08:10.422+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask validate_dataframe
[2025-07-17T19:08:10.439+0000] {task_command.py:423} INFO - Running <TaskInstance: curated_market_dq.validate_dataframe manual__2025-07-17T19:08:05.455518+00:00 [running]> on host 2758917a23bd
[2025-07-17T19:08:10.476+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='curated_market_dq' AIRFLOW_CTX_TASK_ID='validate_dataframe' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T19:08:05.455518+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-17T19:08:05.455518+00:00'
[2025-07-17T19:08:10.494+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-17T19:08:10.495+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-17T19:08:10.496+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T19:08:10.507+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-17T19:08:10.508+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-17T19:08:10.508+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T19:08:10.509+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-17T19:08:10.528+0000] {validator.py:1461} INFO - 	7 expectation(s) included in expectation_suite.
[2025-07-17T19:08:10.557+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/23 [00:00<?, ?it/s]
[2025-07-17T19:08:10.557+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/23 [00:00<?, ?it/s]
[2025-07-17T19:08:10.557+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   9%|8         | 2/23 [00:00<00:00, 4046.60it/s]
[2025-07-17T19:08:10.563+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   9%|8         | 2/23 [00:00<00:00, 341.51it/s] 
[2025-07-17T19:08:10.563+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 495.25it/s]
[2025-07-17T19:08:10.568+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 265.98it/s]
[2025-07-17T19:08:10.574+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 172.05it/s]
[2025-07-17T19:08:10.580+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 129.87it/s]
[2025-07-17T19:08:10.585+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 104.24it/s]
[2025-07-17T19:08:10.591+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 86.64it/s] 
[2025-07-17T19:08:10.597+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 74.34it/s]
[2025-07-17T19:08:10.603+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  13%|#3        | 3/23 [00:00<00:00, 64.56it/s]
[2025-07-17T19:08:10.604+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  22%|##1       | 5/23 [00:00<00:00, 105.54it/s]
[2025-07-17T19:08:10.609+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  22%|##1       | 5/23 [00:00<00:00, 96.09it/s] 
[2025-07-17T19:08:10.611+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  57%|#####6    | 13/23 [00:00<00:00, 239.83it/s]
[2025-07-17T19:08:10.614+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  57%|#####6    | 13/23 [00:00<00:00, 225.97it/s]
[2025-07-17T19:08:10.614+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  57%|#####6    | 13/23 [00:00<00:00, 225.07it/s]
[2025-07-17T19:08:10.615+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  57%|#####6    | 13/23 [00:00<00:00, 224.49it/s]
[2025-07-17T19:08:10.745+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/curated_market_dq_dag.py", line 86, in validate_dataframe
    raise ValueError("❌ GE validation failed")
ValueError: ❌ GE validation failed
[2025-07-17T19:08:10.750+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=curated_market_dq, task_id=validate_dataframe, execution_date=20250717T190805, start_date=20250717T190810, end_date=20250717T190810
[2025-07-17T19:08:10.754+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 24 for task validate_dataframe (❌ GE validation failed; 473)
[2025-07-17T19:08:10.772+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-17T19:08:10.781+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
