[2025-07-19T13:14:52.332+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: build_ml_features.extract_curated scheduled__2025-07-18T00:00:00+00:00 [queued]>
[2025-07-19T13:14:52.335+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: build_ml_features.extract_curated scheduled__2025-07-18T00:00:00+00:00 [queued]>
[2025-07-19T13:14:52.335+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-19T13:14:52.338+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): extract_curated> on 2025-07-18 00:00:00+00:00
[2025-07-19T13:14:52.341+0000] {standard_task_runner.py:60} INFO - Started process 123 to run task
[2025-07-19T13:14:52.343+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'build_ml_features', 'extract_curated', 'scheduled__2025-07-18T00:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/build_ml_features_dag.py', '--cfg-path', '/tmp/tmpfqpfugu0']
[2025-07-19T13:14:52.344+0000] {standard_task_runner.py:88} INFO - Job 67: Subtask extract_curated
[2025-07-19T13:14:52.361+0000] {task_command.py:423} INFO - Running <TaskInstance: build_ml_features.extract_curated scheduled__2025-07-18T00:00:00+00:00 [running]> on host e05da308c0da
[2025-07-19T13:14:52.387+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='build_ml_features' AIRFLOW_CTX_TASK_ID='extract_curated' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-18T00:00:00+00:00'
[2025-07-19T13:14:52.394+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/registry.py", line 236, in get_filesystem_class
    register_implementation(protocol, _import_class(bit["class"]))
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/registry.py", line 271, in _import_class
    mod = importlib.import_module(mod)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 's3fs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/build_ml_features_dag.py", line 43, in extract_curated
    df = pd.read_parquet(CURATED_PATH)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 92, in _get_path_or_handle
    fs, path_or_handle = fsspec.core.url_to_fs(
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/core.py", line 383, in url_to_fs
    chain = _un_chain(url, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/core.py", line 332, in _un_chain
    cls = get_filesystem_class(protocol)
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/registry.py", line 238, in get_filesystem_class
    raise ImportError(bit["err"]) from e
ImportError: Install s3fs to access S3
[2025-07-19T13:14:52.397+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=build_ml_features, task_id=extract_curated, execution_date=20250718T000000, start_date=20250719T131452, end_date=20250719T131452
[2025-07-19T13:14:52.400+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 67 for task extract_curated (Install s3fs to access S3; 123)
[2025-07-19T13:14:52.444+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-19T13:14:52.453+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
